---
title: "Quora text mining"
author: "Minati"
date: "January 10, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df<- getURL('https://www.quora.com/Does-Kurkure-contain-plastic',ssl.verifypeer = FALSE)

class(df)
is.vector(df)
print(df)
install.packages('XML')
library('XML')
df<-htmlTreeParse(df, useInternal = TRUE)
print(df)
df.parse<- unlist(xpathApply(df, path = "//p", fun = xmlValue))
class(df.parse)
print(df.parse)

```


```{r}
df.txt<- NULL
for(i in 2:(length(df.parse)-1)){
  df.txt <- paste(df.txt,as.character(df.parse[i]), sep = ' ') 
}

is.vector(df.txt)  
length(df.txt)
print(df.txt)

```

```{r}
library('tm')
df.txt<- gsub('\r?\n|\r', "", df.txt)
my.corpus<-Corpus(VectorSource(df.txt))
strwrap(my.corpus[[1]])

my.corpus<- tm_map(my.corpus, tolower)
my.corpus<- tm_map(my.corpus, removePunctuation)
my.corpus<- tm_map(my.corpus, stripWhitespace)
my.corpus<- tm_map(my.corpus, removeWords, stopwords('english'))
my.corpus<- tm_map(my.corpus, PlainTextDocument)
strwrap(my.corpus[[1]])

tdm<- TermDocumentMatrix(my.corpus)
inspect(tdm[1:10,])


```



```{r}
library(wordcloud)
my.word.matrix<- as.matrix (tdm)
v<- sort(rowSums(my.word.matrix), decreasing = TRUE)
d<- data.frame(word = names(v), freq = v)
par(bg = 'black')
wordcloud(d$word, d$freq, random.order = FALSE, max.words = 30, color = "gold")

```



